### ISSUE TITLE
[1pt] Create basic structure for Missions - Setup

### ISSUE THREAD

**Issue by Mesi21** [Mesi21/Space-Travelers#20]
- Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.

**Comment by Kingstalux** [comment]
Hi @Mesi21 and @wuletawwonte, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f644550476b6e5269456e6965632f67697068792e676966](https://user-images.githubusercontent.com/85113567/167562079-6d856229-ef73-475c-b1da-1be1d35e2b46.gif)

## Invalid Code Review Request ❌ 

- [ ] Kindly create a new issue to submit for your kanban review and in the issue description you should put the link to your GitHub project and the number of persons working on the project. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
