### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by Mesi21** [Mesi21/Space-Travelers#25]
https://github.com/Mesi21/Space-Travelers
2 persons: 
- @Mesi21 
- @wuletawwonte

**Comment by Meltrust** [comment]
Hi @Mesi21,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- Nice start✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] The total number of cards for 2 people should be 17, but your project contains 16. Please add the one that is missing.
- [ ] All the cards should have at least one person assigned, in a fair and equal way according to the points of each activity.  Please add assignees to all the cards.  The group tasks could have both people if desired.

Please, implement these changes, so your Kaban Board is complete, equal, and fair. 💪 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @Mesi21, and @wuletawwonte👋, 

Well set up the kanban board. ✔️
Your project is complete!  There is nothing else to say other than... it's time to close it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
